<?php

declare(strict_types=1);

$projectRoot = dirname(__DIR__);
$apiDirectory = $projectRoot . '/src/Api';
$targetFile = $projectRoot . '/src/Generated/ApiClientMethods.php';

$apiFiles = glob($apiDirectory . '/*/*.php') ?: [];
sort($apiFiles);

$methodMap = [];
$duplicates = [];

foreach ($apiFiles as $apiFile) {
    $category = basename(dirname($apiFile));
    $className = basename($apiFile, '.php');

    if (isset($methodMap[$className])) {
        $duplicates[$className][] = $category;
        continue;
    }

    $methodMap[$className] = $category;
}

if ($duplicates !== []) {
    fwrite(STDERR, "Duplicate API client methods detected:\n");

    foreach ($duplicates as $className => $categories) {
        $allCategories = array_merge([$methodMap[$className]], $categories);
        fwrite(STDERR, sprintf("- %s: %s\n", $className, implode(', ', $allCategories)));
    }

    exit(1);
}

$content = <<<'PHP'
<?php

declare(strict_types=1);

/**
 * This file is part of KwaiShopSDK.
 *
 * @link     https://github.com/whalesky-labs/kwaishop-php-sdk
 * @document https://github.com/whalesky-labs/kwaishop-php-sdk
 * @contact  westng
 * @license  https://github.com/whalesky-labs/kwaishop-php-sdk/blob/main/LICENSE
 *
 * This file is auto-generated by scripts/generate-api-client-methods.php.
 */

namespace KwaiShopSDK\Generated;

use KwaiShopSDK\Client\PendingRequest;

trait ApiClientMethods
{
PHP;

foreach ($methodMap as $className => $category) {
    $content .= sprintf(
        "\n    public function %s(mixed ...\$arguments): PendingRequest\n    {\n        return \$this->forwardExplicitApiCall(__FUNCTION__, \$arguments, \\KwaiShopSDK\\Api\\%s\\%s::class);\n    }\n",
        $className,
        $category,
        $className
    );
}

$content .= "}\n";

file_put_contents($targetFile, $content);

fwrite(STDOUT, sprintf("Generated %d API client methods into %s\n", count($methodMap), $targetFile));
